# Generated by Django 2.2.12 on 2023-03-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0026_auto_20230309_2026'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jadwal',
            unique_together={('hari', 'waktu')},
        ),
    ]
