# Generated by Django 2.2.12 on 2023-03-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0027_auto_20230315_2110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jadwal',
            unique_together=set(),
        ),
    ]
