# Generated by Django 2.2.12 on 2023-03-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0028_auto_20230315_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matakuliah',
            old_name='matkul',
            new_name='matakuliah',
        ),
    ]
